[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate --schema=packages/data/prisma/schema.prisma"

[deploy]
startCommand = "sh -c 'npx ts-node apps/discord-bot/src/bot.ts'"
healthcheckPath = "/health"
restartPolicyType = "always"

[env]
NODE_ENV = "production"
SERVICE = "discord"
