[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:discord && npx prisma generate --schema=packages/data/prisma/schema.prisma"

[deploy]
startCommand = "node apps/discord-bot/dist/bot.js"
restartPolicyType = "always"

[env]
NODE_ENV = "production"
SERVICE = "discord"
