import { PrismaClient } from '@prisma/client';
import { randomUUID } from 'crypto';
import { DiscordUserMapping } from '../types/discord';
import { authLogger } from '../utils/logger';
import { orchestratorApi } from './orchestratorApi';

// Note: We'll extend the existing Prisma schema to include Discord user mappings
// For now, we'll use a simple in-memory store and prepare for database integration

export class UserService {
  private prisma: PrismaClient | null = null;
  private userMappings = new Map<string, DiscordUserMapping>();

  constructor() {
    try {
      // Enhanced debugging for database connection
      const databaseUrl = process.env.DATABASE_URL;
      authLogger.info({
        hasDatabaseUrl: !!databaseUrl,
        databaseUrlLength: databaseUrl?.length || 0,
        databaseUrlHost: databaseUrl ? new URL(databaseUrl).host : 'none'
      }, 'Discord bot database configuration');

      // If DATABASE_URL is not defined for the bot, default to in-memory
      if (!databaseUrl) {
        authLogger.error('❌ CRITICAL: No DATABASE_URL configured for discord-bot; using in-memory user store');
        authLogger.error('🔧 This will cause authentication to not persist! Set DATABASE_URL to same value as orchestrator');
        this.prisma = null;
        return;
      }

      this.prisma = new PrismaClient({
        log: ['error', 'warn'],
      });
      
      // Attempt a background connect; on failure, fall back to in-memory
      this.prisma
        .$connect()
        .then(() => {
          authLogger.info('✅ Successfully connected to database for user service');
          // Test the connection by attempting a simple query
          return this.prisma!.discordUser.count();
        })
        .then((count) => {
          authLogger.info({ discordUserCount: count }, '✅ Database connection verified - Discord users table accessible');
        })
        .catch((error) => {
          authLogger.error({ error: error.message }, '❌ Database connect failed, using in-memory store');
          authLogger.error('🔧 This will cause authentication to not persist! Check DATABASE_URL and network connectivity');
          this.prisma = null;
        });
    } catch (error) {
      authLogger.error(error, '❌ Database initialization failed, using in-memory store');
      authLogger.error('🔧 This will cause authentication to not persist!');
      this.prisma = null;
    }
  }

  async getUser(discordId: string): Promise<DiscordUserMapping | null> {
    try {
      if (this.prisma) {
        const user = await this.prisma.discordUser.findUnique({
          where: { discordId },
          include: { user: true }
        });
        
        if (user) {
          return {
            discordId: user.discordId,
            discordUsername: user.discordUsername,
            yahooUserId: user.userId,
            isAuthenticated: user.isAuthenticated,
            createdAt: user.createdAt,
            updatedAt: user.updatedAt
          };
        }
      }
      // Fallback to in-memory store if prisma not available or no record
      return this.userMappings.get(discordId) || null;
    } catch (error) {
      authLogger.error({ error, discordId }, 'Failed to get user (falling back to in-memory)');
      return this.userMappings.get(discordId) || null;
    }
  }

  async createOrUpdateUser(discordId: string, discordUsername: string): Promise<DiscordUserMapping> {
    try {
      if (this.prisma) {
        // Upsert to avoid race conditions - id will be auto-generated by cuid()
        const user = await this.prisma.discordUser.upsert({
          where: { discordId },
          update: {
            discordUsername,
            updatedAt: new Date(),
          },
          create: {
            discordId,
            discordUsername,
            isAuthenticated: false,
          },
          include: { user: true },
        });
        authLogger.info({ discordId, discordUsername }, 'Upserted user mapping');
        
        return {
          discordId: user.discordId,
          discordUsername: user.discordUsername,
          yahooUserId: user.userId,
          isAuthenticated: user.isAuthenticated,
          createdAt: user.createdAt,
          updatedAt: user.updatedAt
        };
      }

      // Fallback to in-memory store
      const userData: DiscordUserMapping = {
        discordId,
        discordUsername,
        yahooUserId: undefined,
        isAuthenticated: false,
        createdAt: new Date(),
        updatedAt: new Date()
      };

      const existingUser = this.userMappings.get(discordId);
      if (existingUser) {
        existingUser.discordUsername = discordUsername;
        existingUser.updatedAt = new Date();
        this.userMappings.set(discordId, existingUser);
        return existingUser;
      }

      this.userMappings.set(discordId, userData);
      authLogger.info({ discordId, discordUsername }, 'Created new user mapping (in-memory)');
      return userData;
    } catch (error) {
      // On any Prisma error, fall back to in-memory
      authLogger.warn({ error, discordId, discordUsername }, 'DB upsert failed, using in-memory user store');
      const existing = this.userMappings.get(discordId);
      if (existing) {
        existing.discordUsername = discordUsername;
        existing.updatedAt = new Date();
        this.userMappings.set(discordId, existing);
        return existing;
      }
      const userData: DiscordUserMapping = {
        discordId,
        discordUsername,
        yahooUserId: undefined,
        isAuthenticated: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      this.userMappings.set(discordId, userData);
      return userData;
    }
  }

  async linkYahooAccount(discordId: string, yahooUserId: string): Promise<void> {
    try {
      if (this.prisma) {
        await this.prisma.discordUser.update({
          where: { discordId },
          data: { 
            userId: yahooUserId,
            isAuthenticated: true,
            updatedAt: new Date(),
          }
        });
        
        authLogger.info({ discordId, yahooUserId }, 'Linked Yahoo account');
        return;
      }

      const user = this.userMappings.get(discordId);
      if (user) {
        user.yahooUserId = yahooUserId;
        user.isAuthenticated = true;
        user.updatedAt = new Date();
        this.userMappings.set(discordId, user);
      }

      authLogger.info({ discordId, yahooUserId }, 'Linked Yahoo account (in-memory)');
    } catch (error) {
      authLogger.warn({ error, discordId, yahooUserId }, 'DB link failed, using in-memory user store');
      const user = this.userMappings.get(discordId) || {
        discordId,
        discordUsername: discordId,
        yahooUserId: null,
        isAuthenticated: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      user.yahooUserId = yahooUserId;
      user.isAuthenticated = true;
      user.updatedAt = new Date();
      this.userMappings.set(discordId, user);
    }
  }

  async unlinkYahooAccount(discordId: string): Promise<void> {
    try {
      if (this.prisma) {
        await this.prisma.discordUser.update({
          where: { discordId },
          data: { 
            userId: null,
            isAuthenticated: false,
            updatedAt: new Date(),
          }
        });
        
        authLogger.info({ discordId }, 'Unlinked Yahoo account');
        return;
      }

      const user = this.userMappings.get(discordId);
      if (user) {
        user.yahooUserId = undefined;
        user.isAuthenticated = false;
        user.updatedAt = new Date();
        this.userMappings.set(discordId, user);
      }

      authLogger.info({ discordId }, 'Unlinked Yahoo account (in-memory)');
    } catch (error) {
      authLogger.warn({ error, discordId }, 'DB unlink failed, using in-memory user store');
      const user = this.userMappings.get(discordId);
      if (user) {
        user.yahooUserId = undefined;
        user.isAuthenticated = false;
        user.updatedAt = new Date();
        this.userMappings.set(discordId, user);
      }
    }
  }

  async isAuthenticated(discordId: string): Promise<boolean> {
    const user = await this.getUser(discordId);
    return user?.isAuthenticated || false;
  }

  async getYahooUserId(discordId: string): Promise<string | null> {
    const user = await this.getUser(discordId);
    return user?.yahooUserId || null;
  }

  async getAllUsers(): Promise<DiscordUserMapping[]> {
    try {
      if (this.prisma) {
        const users = await this.prisma.discordUser.findMany({
          include: { user: true }
        });
        
        return users.map(user => ({
          discordId: user.discordId,
          discordUsername: user.discordUsername,
          yahooUserId: user.userId,
          isAuthenticated: user.isAuthenticated,
          createdAt: user.createdAt,
          updatedAt: user.updatedAt
        }));
      }
      
      return Array.from(this.userMappings.values());
    } catch (error) {
      authLogger.warn(error, 'DB fetch failed, returning in-memory users');
      return Array.from(this.userMappings.values());
    }
  }

  async cleanup(): Promise<void> {
    if (this.prisma) {
      await this.prisma.$disconnect();
    }
  }

  /**
   * Attempt to reconcile auth status from the orchestrator. If orchestrator reports
   * the user (by discordId) is authenticated, link locally and return true.
   */
  async ensureAuthenticated(discordId: string, discordUsername: string): Promise<boolean> {
    try {
      // Ensure a local record exists first
      await this.createOrUpdateUser(discordId, discordUsername);

      const status = await orchestratorApi.checkOAuthStatus(discordId);
      if (status?.authenticated) {
        await this.linkYahooAccount(discordId, discordId);
        return true;
      }
      return false;
    } catch (error) {
      authLogger.warn({ error, discordId }, 'Failed to ensure authentication via orchestrator');
      return false;
    }
  }
}

export const userService = new UserService();
